### ISSUE TITLE
issues with code link 

### ISSUE THREAD

**Issue by Aymenayachi** [riccardopezzoni/Covid-19_Impact_on_Mobile_Networks#1]
hello sir  I have issues with google collab link [](https://colab.research.google.com/drive/1AP5TiSwLySGQaKAvDw5l3YITxhAAw5tL?authuser=2#scrollTo=I_NqoNv35lwc)  i wonder if you can help me 
![image_2023-04-05_020234344](https://user-images.githubusercontent.com/130014073/230251513-b7b9f16f-e9b6-433a-93fa-dbb89b77a9a5.png)

**Comment by riccardopezzoni** [comment]
I have uploaded the full Jupiter notebook to GitHub here https://github.com/riccardopezzoni/Covid-19_Impact_on_Mobile_Networks/blob/main/MRN_Project2.ipynb 
Late me know if you can see it now

**Comment by Aymenayachi** [comment]
Very good. I Access to the code .
Thank you
